# ---------------------------------------------------------------------
# Copyright (c) 2025 Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause
# ---------------------------------------------------------------------

from __future__ import annotations

import logging
from collections.abc import Generator
from contextlib import contextmanager

import torch


def flatten(obj: list | tuple) -> list:
    """Flatten nested list or tuple"""
    tgt_type = (list, tuple)  # targeted types
    flattened_list = []
    for item in obj:
        if isinstance(item, tgt_type):
            flattened_list.extend(flatten(item))
        else:
            flattened_list.append(item)
    return flattened_list


@contextmanager
def suppress_warnings() -> Generator[None, None, None]:
    """
    Suppresses warning generated by block called within.
    This is helpful to supress warning when one loads part of the model and
    sub-module throws warning which should be ignored for clean UX.
    """
    old_level = logging.root.manager.disable
    logging.disable(logging.WARNING)
    try:
        yield
    finally:
        logging.disable(old_level)


class Conv2dLinear(torch.nn.Module):
    """
    A class to convert a Linear layer to a Conv2D layer with a 1x1 kernel.

    This allows the linear transformation to be applied to the channel dimension
    at each spatial location in the input tensor.

    Parameters
    ----------
    linear
        The original linear layer to be converted.
    """

    def __init__(self, linear: torch.nn.Linear) -> None:
        super().__init__()
        self.in_features = linear.in_features
        self.out_features = linear.out_features

        # Initialize a Conv2D layer with a 1x1 kernel to mimic the Linear layer
        self.conv = torch.nn.Conv2d(
            in_channels=self.in_features,
            out_channels=self.out_features,
            kernel_size=1,
            bias=(linear.bias is not None),
        )

        # Copy the weights from the Linear layer to the Conv2D layer
        self.conv.weight.data.copy_(
            linear.weight.data.view(self.out_features, self.in_features, 1, 1)
        )

        # Copy the bias if it exists
        if linear.bias is not None and self.conv.bias is not None:
            self.conv.bias.data.copy_(linear.bias.data)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        Forward-pass routine for the Conv2D layer.

        Parameters
        ----------
        x
            The input tensor in NCHW format.

        Returns
        -------
        output_tensor : torch.Tensor
            The output tensor after applying the Conv2D transformation.
        """
        return self.conv(x)


class Conv2dFromConv1d(torch.nn.Module):
    """Adapt a Conv1d layer to an equivalent Conv2d layer for inputs of shape N,C,1,L."""

    def __init__(self, module: torch.nn.Conv1d) -> None:
        super().__init__()
        padding: tuple[int, int] | str
        if isinstance(module.padding, str):
            padding = module.padding
        else:
            padding = (0, module.padding[0])

        self.conv = torch.nn.Conv2d(
            in_channels=module.in_channels,
            out_channels=module.out_channels,
            kernel_size=(1, module.kernel_size[0]),
            stride=(1, module.stride[0]),
            padding=padding,
            dilation=(1, module.dilation[0]),
            groups=module.groups,
            bias=module.bias is not None,
        ).to(device=module.weight.device, dtype=module.weight.dtype)
        self.conv.train(module.training)

        with torch.no_grad():
            self.conv.weight.copy_(module.weight.unsqueeze(-2))
            if module.bias is not None and self.conv.bias is not None:
                self.conv.bias.copy_(module.bias)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.conv(x)


class InstanceNorm2dFromInstanceNorm1d(torch.nn.Module):
    """Adapt an InstanceNorm1d layer to an equivalent InstanceNorm2d layer."""

    def __init__(self, module: torch.nn.InstanceNorm1d) -> None:
        super().__init__()
        if module.momentum is None:
            raise ValueError("InstanceNorm1d momentum must be a float")
        self.norm = torch.nn.InstanceNorm2d(
            num_features=module.num_features,
            eps=module.eps,
            momentum=module.momentum,
            affine=module.affine,
            track_running_stats=module.track_running_stats,
        )
        reference = module.weight if module.weight is not None else module.running_mean
        if reference is not None:
            self.norm.to(device=reference.device, dtype=reference.dtype)
        self.norm.train(module.training)

        with torch.no_grad():
            if module.weight is not None and self.norm.weight is not None:
                self.norm.weight.copy_(module.weight)
            if module.bias is not None and self.norm.bias is not None:
                self.norm.bias.copy_(module.bias)
            if module.running_mean is not None and self.norm.running_mean is not None:
                self.norm.running_mean.copy_(module.running_mean)
            if module.running_var is not None and self.norm.running_var is not None:
                self.norm.running_var.copy_(module.running_var)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.norm(x)
